### ISSUE TITLE
Docker verveinej v3.0.8 does not handle correctly option -o

### ISSUE THREAD

**Issue by PatriciaTot** [moosetechnology/VerveineJ#82]
`docker run -v /home/users/etudiant/projet_totoum_patricia_coo/:/src -v /home/users/etudiant/dependanceProjetCompetitions/:/dependency ghcr.io/evref-bl/verveinej:v3.0.8 -format json -o competitions.json .`

Generates output.mse file

**Comment by badetitou** [comment]
Hello

Indeed, there were a problem with the project https://github.com/Evref-BL/VerveineJ-Docker.
I tried a fix this morning. 
You might be able to do what you want now with 

```sh
docker run -v /home/users/etudiant/projet_totoum_patricia_coo/:/src -v /home/users/etudiant/dependanceProjetCompetitions/:/dependency ghcr.io/evref-bl/verveinej:main -format json -o competitions.json
```

Also, please note that you **must** not add a `.` at the end of the line

> The fix will be added to `v3.0.13` when the main VerveineJ project will evolve as well


Please, tell me if the fix is ok for you, and close the issue if everything is alright now
